# Default Configuration - OpenAPI Services
# This is the default configuration using OpenAPI JSON

services:
  - digital_sales:
      url: https://digitalsales.19pc1vtv090u.us-east.codeengine.appdomain.cloud/openapi.json
      description: This Digital Sales Skills API provides sales professionals with a unified interface to access territory accounts, retrieve client information from TPP, manage job roles, and synchronize contacts between Zoominfo and Salesloft—streamlining the process of managing customer relationships and sales data across multiple platforms.

# MCP Servers Configuration (commented out by default)
# Uncomment the sections below to enable MCP servers
# Supports multiple transport types: stdio, sse, http

# mcpServers:
#   # SSE Transport - Digital Sales MCP Server
#   # Will timeout after 15 seconds and fall back to mock implementation
#   digital_sales:
#     url: https://digitalsales-mcp.19pc1vtv090u.us-east.codeengine.appdomain.cloud/sse
#     transport: sse
#     description: Digital Sales MCP Server for handling real-time events and interactions.

#   # STDIO Transport - Local file system operations
#   filesystem:
#     command: npx
#     args: ["-y", "@modelcontextprotocol/server-filesystem", "./cuga_workspace"]
#     transport: stdio  # Optional: auto-detected when command is present
#     description: Standard file system operations for workspace management
#     env:
#       LOG_LEVEL: INFO  # Environment variables for STDIO transport

# Additional Examples:

# HTTP Transport (Streamable HTTP - recommended for production)
# mcpServers:
#   production_service:
#     url: https://api.example.com/mcp
#     transport: http
#     description: Production MCP server with HTTP transport

# STDIO Transport (local command-based servers - default for commands)
# mcpServers:
#   filesystem:
#     command: npx
#     args: ["-y", "@modelcontextprotocol/server-filesystem", "./cuga_workspace"]
#     transport: stdio  # Optional: auto-detected when command is present
#     description: Local file system operations
#     env:
#       LOG_LEVEL: DEBUG

# Python STDIO Transport
# mcpServers:
#   local_python:
#     command: python
#     args: ["./my_server.py"]
#     env:
#       API_KEY: your_api_key
#       DEBUG: "true"
#     description: Local Python MCP server

# SSE Transport (legacy - superseded by HTTP for new deployments)
# mcpServers:
#   digital_sales_local:
#     url: http://127.0.0.1:8000/sse
#     transport: sse
#     description: Local Digital Sales API
